accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),
    name='login'),
    path('logout/', auth_views.LogoutView.as_view(),name='logout'),
    path('signup/', views.SignUpView.as_view(),name='signup'),
    
]

groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('',views.ListGroups.as_view(),name='all'),
    path('new/', views.CreateGroup.as_view(),name='create'),
    path('posts/in/<str:slug>/', views.SingleGroup.as_view(),name='single'),
    path('join/<str:slug>/', views.JoinGroup.as_view(), name='join'),
    path('leave/<str:slug>/', views.LeaveGroup.as_view(), name='leave'),

    
]

posts/urls.py
from django.urls import  path
from . import views
app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(),name='all'),
    path('new/', views.CreatePost.as_view(),name='create'),
    path('by/<str:username>/', views.UserPosts.as_view(),name='for_user'),
    path('by/<str:username>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(),name='delete'),

]

socialsite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls'),name='accounts'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include('posts.urls'),name='posts'),
    path('groups/', include('groups.urls'),name='groups')
    
]

templates/base.html
{% load static %}
<html>
    <head>
        <title>Social Site</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'socialsite/css/master.css' %}">
    </head>
    <body>
        <nav class="navbar mynav" role="navigation" id="navbar">
            <div class="container">
                <a class="navbar-brand mynav" href="{% url 'home' %}">Social Site</a>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li class="nav-item"><a href="{% url 'posts:create' %}">Post</a></li>
                    <li class="nav-item"><a href="{% url 'groups:all' %}">Groups</a></li>
                    <li class="nav-item"><a href="{% url 'groups:create' %}">Create Group</a></li>
                    <li class="nav-item"><a href="{% url 'accounts:logout' %}">Log Out</a></li>
                    {% else %}
                    <li class="nav-item"><a href="{% url 'groups:all' %}">Groups</a></li>
                    <li class="nav-item"><a href="{% url 'accounts:login' %}">Log In</a></li>
                    <li class="nav-item"><a href="{% url 'accounts:signup' %}">SignUp</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>  
        <div class="container mycontent ">
        {% block content %}

        {% endblock %}
    </div>
    </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Welcome to Social Blog.</h1>
<p>Here you can create different groups. Posts can be made in different groups.</p>
<p>Leave or join a group anytime. :)</p>
{% endblock %}

templates/test.html
{% extends 'base.html' %}

{% block content %}
<h2>You are now logged in.</h2>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}

{% block content %}
<h2>You are now logged out.</h2>
{% endblock %}